name: Build the Python app
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
    push:
        branches: ["main", "develop"]
    pull_request:
        branches: ["main"]

env:
    PYTHON_VERSION: 3.13

jobs:
    python-ci:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python version ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                python-version: '${{ env.PYTHON_VERSION }}'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 coverage
                  pip install -r requirements.txt

            - name: Code Style Check
              run:  |
                cd ../
                flake8 . --show-source --statistics --exit-zero

            - name: Code Complexity Check
              run: |
                cd ../
                flake8 . --statistics --max-complexity=10 --exit-zero

            - name: Run Tests
              run: python manage.py test -v2
  
            - name: Generate Coverage
              run: coverage run --source='.' manage.py test -v2
  
            - name: Display Coverage
              run: coverage report

            - name: Upload the code as an artifact
              uses: actions/upload-artifact@v4
              with:
                name: Python App
                path: .
